### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by jegjessing** [DavidAlloza/SNASharp#1]
All sorts of warning about files missing.

How to reproduce
1. git clone https://github.com/DavidAlloza/SNASharp.git
2. Open solution in Visual studio 2019
3. Select rebuild solution

Result:
![image](https://user-images.githubusercontent.com/12476410/123074480-a1463000-d417-11eb-9889-59335eabd2ee.png)
Expected result:
Solution should have compiled fine

I followed the above steps, I did not add, edit or remove any files

**Comment by DavidAlloza** [comment]
Thank you for your report jegjessing ,
is a dependence issue (file shared with multiple project) , i will fix it in the next weeks.
Temporary, as workaround,  you can duplicate Utility.cs from SNASharp\SNASharp to SNASharp\NWTInterface

**Comment by DavidAlloza** [comment]
I juste added (duplicated) the file
This is not a definitive solution, but the project will build.

**Comment by jegjessing** [comment]
Fantastic. Thanks
*Med venlig hilsen / Best regards*
Jarl Gjessing
Mobil: +45 60 72 17 16
Adresse: Klintevej 7, DK-3600 Frederikssund
